### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by galaczi** [kbrgl/svelte-french-toast#64]
The toast messages look absolutely amazing! However, judging from the issues, I have a feeling it's no longer maintained. Especially this: https://github.com/kbrgl/svelte-french-toast/issues/61 Is it maintained?

**Comment by galaczi** [comment]
FYI, I found a maintained version: https://github.com/jill64/svelte-toast

**Comment by kbrgl** [comment]
Hey @galaczi, this package is still maintained—most of the issues that roll in tend to be build issues or otherwise lower priority, but I’ll be fixing any higher priority bugs if any are reported.

**Comment by binury** [comment]
> Hey @galaczi, this package is still maintained—most of the issues that roll in tend to be build issues or otherwise lower priority, but I’ll be fixing any higher priority bugs if any are reported.

Hey @kbrgl JSYK -heads up- you have been making commits but not releasing/versioning them. So, when one installs french-toast they are unfortunately left to use whatever the last update was… which was in July of last year.
In particular, commit 509d6752fc is missing and is arguably essential. Because your package must be built to generate dist (which is by no means unusual), it is not possible for one to work around this dilemma by installing french-toast by version or tag (e.g., `npm install svelte-french-toast@master`. As a last resort one must resign to [forking this package on npm](https://www.npmjs.com/package/@teddy-error/svelte-french-toast) in order to pull in code that you haven't versioned and created a release for.
