### ISSUE TITLE
Toast position not working properly in electron

### ISSUE THREAD

**Issue by karmaral** [kbrgl/svelte-french-toast#7]
Hello. The positioning of the toast appears to malfunction inside electron.
I'm not sure if it's electron specific or rather the `create-svelte-electron-app` template. 

I tried it on a repl and it works just fine, but using electron, the position seems to be stuck to the top-left. The toasts also don't stack. It would seem the inline styling is not getting applied to the elements.

I've created a blank project with the issue. If you clone it and try to run it, the problem should be apparent.
[Here is the link](https://github.com/karmaral/svelte-french-toast-electron-issue)

**Comment by kbrgl** [comment]
Thank you for opening an issue and including a repo that reproduces it!

From a cursory look, it appears that the issue is not with Svelte French Toast but with the template. On opening the browser devtools, it's clear that the build system isn't correctly configured to compile [style directives](https://svelte.dev/tutorial/style-directive):

<img width="1254" alt="Screen Shot 2022-07-21 at 11 45 58 PM" src="https://user-images.githubusercontent.com/13417496/180379948-cde62bb2-3e91-4e54-abc3-3deac8934ee1.png">

You likely need to change rollup.config.js to correctly compile them. Here's the rollup.config.js that was used in Svelte French Toast before I switched to SvelteKit's library mode. You can try using it to fix your issue:

https://github.com/kbrgl/svelte-french-toast/blob/910f0dff30fc07398272ede7dca1adb2430ed445/packages/svelte-french-toast/rollup.config.js

**Comment by kbrgl** [comment]
Yep, that was the issue. Here's a working version of your repo with a fixed rollup configuration:

https://github.com/kbrgl/svelte-french-toast-electron-issue
